### ISSUE TITLE
After filtering the feeds from the date filter user unable to get all feeds

### ISSUE THREAD

**Issue by Jabiulla24** [janastu/iihs_curation_dashboard#118] opened 2018-02-06 16:10 UTC
After creating new feeds when the user filters from the date filter, the view displays filter from the date mentioned but if the user wants to view all feeds there is no option for returning to all feeds if user clicks on category name.

I think you need to clear the form of date filter so that it works.

**Comment by vaishnavisv** [comment] 2018-03-12 08:21
Duplicate of #104

**Closed** 2018-04-26 15:53 UTC
Labels: bug, resolved
